baseURL = "https://powersj.io"
title = "Joshua Powers"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 20

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true

[params]
author = "Joshua Powers"
description = "The personal blog of Joshua Powers (powersj). Musings about Ubuntu, Python, Go, the Cloud, and other things I come across."
keywords = "ubuntu,blog,developer,personal"
info = "Seek out, explore, and build things"

#gravatar = ""
#avatarURL = "images/avatar.jpg"
footerContent = "<a href='https://github.com/powersj/powersj.io/issues/new'>Report a bug on this site</a>"
dateFormat = "January 2, 2006"
hideFooter = false
hideCopyright = false
hideCredits = true

# Right To Left, shift content direction for languagues such as Arabic
rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false

# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Enable Inline Shortcodes
enableInlineShortcodes = true
# Custom CSS
customCSS = ["css/custom.css"]
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'", "https://www.gravatar.com"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[languages.en]
languageName = "American English"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"
pre = "fa-pencil"

[[languages.en.menu.main]]
name = "Journey"
weight = 2
url = "journey/"
pre = "fa-plane"

[[languages.en.menu.main]]
name = "Uses"
weight = 3
url = "uses/"
pre = "fa-briefcase"

[[languages.en.menu.main]]
name = "Afterhours"
weight = 4
url = "afterhours/"
pre = "fa-moon"

[[languages.en.menu.main]]
name = "About"
weight = 5
url = "about/"
pre = "fa-info-circle"
