title = "Joshua Powers"
theme = "powersj-bulma"

baseURL = "https://powersj.io/"
languageCode = "en-us"

[params]
author = "Joshua Powers"
dateFormat = "02 January 2006"
description = "The personal blog of Joshua Powers (powersj). Musings about my work at Canonical with Ubuntu, Python, the Cloud, and other things I come across."
